### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by Flozi95** [ForrestFalcon/fAlarm#11]
Hi,
vielleicht lässt es sich z.b. bei https://github.com/ForrestFalcon/fAlarm/blob/master/app/src/main/res/values/strings.xml#L22 realisieren, dass man ein Emoji anzeigt und kein :=)

**Comment by kvn-stgl** [comment]
Wird es auf die schnelle nicht geben. Habe gerade festgestellt, dass Android unter Version 5.0 nicht mit Emoticons in Strings umgehen kann ;)

**Comment by Flozi95** [comment]
Dann nimm se am besten raus.
